# Generated by Django 6.0.5 on 2026-05-12 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('tenant_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, max_length=1000, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('gst', models.CharField(blank=True, max_length=20, null=True)),
                ('pan', models.CharField(blank=True, max_length=20, null=True)),
                ('website_url', models.CharField(blank=True, max_length=100, null=True)),
                ('website_name', models.CharField(blank=True, max_length=50, null=True)),
                ('tenant_logo_s3_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('tenant_favicon_s3_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user_TenantProfile', to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.currency')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.state')),
            ],
            options={
                'ordering': ('tenant_name',),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
                ('role_short_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('system_role_id', models.IntegerField(blank=True, null=True)),
                ('sequence', models.IntegerField(default=0)),
                ('group', models.ManyToManyField(related_name='RoleGroup', to='auth.group')),
                ('tenantProfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenantProfile_Role', to='tenant.tenantprofile')),
            ],
            options={
                'ordering': ('role_name',),
            },
        ),
    ]
