# Generated by Django 6.0.5 on 2026-05-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, related_name='RoleGroup', to='auth.group'),
        ),
    ]
