# Generated by Django 6.0.5 on 2026-05-13 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_alter_role_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialConnectionType',
            fields=[
                ('social_connection_id', models.AutoField(primary_key=True, serialize=False)),
                ('social_connection_name', models.CharField(max_length=100)),
                ('social_connection_icon', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('social_connection_name',),
            },
        ),
        migrations.CreateModel(
            name='SocialConnection',
            fields=[
                ('social_connection_id', models.AutoField(primary_key=True, serialize=False)),
                ('social_connection_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_SocialConnection', to='tenant.tenantprofile', verbose_name='Company')),
                ('socialConnectionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialConnectionType_SocialConnection', to='tenant.socialconnectiontype')),
            ],
            options={
                'ordering': ('socialConnectionType__social_connection_name',),
            },
        ),
    ]
