# Generated by Django 6.0.5 on 2026-05-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_socialconnectiontype_socialconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='time_zone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
