# Generated by Django 6.0.5 on 2026-05-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_tenantprofile_date_formate_view_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateFormat',
            fields=[
                ('date_format_id', models.AutoField(primary_key=True, serialize=False)),
                ('format_value', models.CharField(max_length=50, unique=True)),
                ('display_label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_label',),
            },
        ),
        migrations.CreateModel(
            name='TimeFormat',
            fields=[
                ('time_format_id', models.AutoField(primary_key=True, serialize=False)),
                ('format_value', models.CharField(max_length=50, unique=True)),
                ('display_label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_label',),
            },
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('time_zone_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_zone_name', models.CharField(max_length=100, unique=True)),
                ('display_label', models.CharField(max_length=200)),
                ('utc_offset', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('time_zone_name',),
            },
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='date_formate_view',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='time_formate_view',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='time_zone',
        ),
    ]
