# Generated by Django 6.0.5 on 2026-05-14 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_dateformat_timeformat_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='date_formate_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.dateformat'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='time_formate_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.timeformat'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='time_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.timezone'),
        ),
    ]
