# Generated by Django 6.0.5 on 2026-05-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0007_tenantprofile_date_formate_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
