# Generated by Django 6.0.5 on 2026-05-16 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('masters', '0004_district_masters_dis_state_i_025d22_idx_and_more'),
        ('tenant', '0008_role_role_desc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['tenantProfile'], name='tenant_role_tenantP_0f7be2_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantprofile',
            index=models.Index(fields=['tenant_name'], name='tenant_tena_tenant__9f9a85_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantprofile',
            index=models.Index(fields=['is_active'], name='tenant_tena_is_acti_65fd0c_idx'),
        ),
    ]
