# Generated by Django 6.0.5 on 2026-05-12 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('country_name',),
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_code', models.CharField(max_length=10)),
                ('currency_symbol', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('currency_code',),
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('gender_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['gender_name'],
            },
        ),
        migrations.CreateModel(
            name='MenuType',
            fields=[
                ('menu_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_type_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('menu_type_name',),
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=100)),
                ('menu_icon', models.CharField(max_length=100)),
                ('menu_slug', models.CharField(blank=True, db_index=True, default='#', max_length=70, null=True)),
                ('menu_args', models.IntegerField(blank=True, null=True)),
                ('sequence_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'menuType__menu_type_id': 2, 'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='masters.menu', verbose_name='Parent')),
                ('menuType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.menutype')),
            ],
            options={
                'ordering': ('sequence_order',),
            },
        ),
        migrations.CreateModel(
            name='Menu_Group',
            fields=[
                ('menu_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_group_name', models.CharField(max_length=400)),
                ('is_active', models.BooleanField(default=True)),
                ('is_permission_required', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('is_write', models.BooleanField(default=False)),
                ('is_create', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_import', models.BooleanField(default=False)),
                ('is_export', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('menu', models.ManyToManyField(to='masters.menu')),
            ],
            options={
                'ordering': ('menu_group_name',),
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.country')),
            ],
            options={
                'ordering': ('state_name',),
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('division_id', models.AutoField(primary_key=True, serialize=False)),
                ('division_code', models.CharField(blank=True, max_length=30, null=True)),
                ('division_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_Division', to='masters.state')),
            ],
            options={
                'ordering': ('division_name',),
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.division')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.state')),
            ],
            options={
                'ordering': ('district_name',),
            },
        ),
    ]
