# Generated by Django 6.0.5 on 2026-05-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_group',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menu_group',
            name='group',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Menu_Group',
        ),
    ]
