# Generated by Django 6.0.5 on 2026-05-12 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('masters', '0002_remove_menu_group_menu_remove_menu_group_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=100)),
                ('menu_icon', models.CharField(max_length=100)),
                ('menu_slug', models.CharField(blank=True, db_index=True, default='#', max_length=70, null=True)),
                ('menu_args', models.IntegerField(blank=True, null=True)),
                ('sequence_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('menuType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.menutype')),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'menuType__menu_type_id': 2, 'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='masters.menu', verbose_name='Parent')),
            ],
            options={
                'ordering': ('sequence_order',),
            },
        ),
        migrations.CreateModel(
            name='Menu_Group',
            fields=[
                ('menu_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_group_name', models.CharField(max_length=400)),
                ('is_active', models.BooleanField(default=True)),
                ('is_permission_required', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('is_write', models.BooleanField(default=False)),
                ('is_create', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_import', models.BooleanField(default=False)),
                ('is_export', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('menu', models.ManyToManyField(to='masters.menu')),
            ],
            options={
                'ordering': ('menu_group_name',),
            },
        ),
    ]
