# Generated by Django 6.0.5 on 2026-05-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_menu_menu_group'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['state'], name='masters_dis_state_i_025d22_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['division'], name='masters_dis_divisio_d0c369_idx'),
        ),
        migrations.AddIndex(
            model_name='division',
            index=models.Index(fields=['state'], name='masters_div_state_i_c87ce2_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['country'], name='masters_sta_country_1e9887_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['state_name'], name='masters_sta_state_n_beabc7_idx'),
        ),
    ]
