# Generated by Django 6.0.5 on 2026-05-23 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_district_masters_dis_state_i_025d22_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('city_name_hindi', models.CharField(blank=True, max_length=100, null=True)),
                ('sequence', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.district')),
            ],
            options={
                'ordering': ('city_name',),
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=100)),
                ('zone_name_hindi', models.CharField(blank=True, max_length=100, null=True)),
                ('sequence', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.district')),
            ],
            options={
                'ordering': ('zone_name',),
            },
        ),
    ]
