# Generated by Django 6.0.5 on 2026-05-25 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_city_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='district',
        ),
        migrations.AddField(
            model_name='district',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.zone'),
        ),
        migrations.AddField(
            model_name='zone',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.state'),
            preserve_default=False,
        ),
    ]
