# Generated by Django 6.0.5 on 2026-05-25 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_remove_zone_district_district_zone_zone_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division_District', to='masters.division'),
        ),
        migrations.AlterField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_District', to='masters.state'),
        ),
        migrations.AlterField(
            model_name='district',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_District', to='masters.zone'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_Zone', to='masters.state'),
        ),
    ]
