# Generated by Django 6.0.5 on 2026-05-25 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_alter_district_division_alter_district_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_Zone', to='masters.state'),
        ),
    ]
