# Generated by Django 6.0.5 on 2026-05-25 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_alter_zone_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='state_Zone', to='masters.state'),
            preserve_default=False,
        ),
    ]
