# Generated by Django 6.0.5 on 2026-05-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_alter_zone_state'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['zone'], name='masters_dis_zone_id_b0a27e_idx'),
        ),
    ]
