# Generated by Django 6.0.5 on 2026-05-29 06:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frvaccident',
            name='frv_accident_unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='frvclaim',
            name='frv_claim_unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='frvcodeviolation',
            name='frv_code_violation_unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='frvconsumable',
            name='frv_consumable_unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='frvconsumabletransaction',
            name='frv_consumable_transaction_unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='frvfuel',
            name='frv_fuel_unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='frvguideline',
            name='frv_guideline_unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='frvinspection',
            name='frv_inspection_unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='frvmaintenance',
            name='frv_maintenance_unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='frvservicecenter',
            name='frv_service_center_unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='frvtakeoverhandover',
            name='frv_handover_takeover_unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
