# Generated by Django 6.0.5 on 2026-05-26 08:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0010_district_masters_dis_zone_id_b0a27e_idx'),
        ('setup', '0009_remove_policestation_city_and_more'),
        ('tenant', '0009_role_tenant_role_tenantp_0f7be2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRequestType',
            fields=[
                ('employee_request_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_request_type_name', models.CharField(max_length=200)),
                ('employee_request_type_css', models.CharField(blank=True, max_length=200, null=True)),
                ('employee_request_type_icon', models.CharField(blank=True, max_length=200, null=True)),
                ('sequence', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sequence',),
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('employee_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_status_name', models.CharField(max_length=200)),
                ('employee_status_css', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('employee_status_id',),
            },
        ),
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('remark', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('employee_code', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField()),
                ('picture', models.CharField(blank=True, max_length=500, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=20)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('profile_completion_percentage', models.IntegerField(default=0)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('current_address', models.TextField(blank=True, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('employment_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Resigned', 'Resigned'), ('Terminated', 'Terminated')], default='Active', max_length=20)),
                ('work_location', models.CharField(blank=True, max_length=100)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_address', models.CharField(blank=True, max_length=500)),
                ('bank_account_number', models.CharField(blank=True, max_length=30)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('relationship', models.CharField(blank=True, max_length=50)),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country_EmployeeInfo', to='masters.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_EmployeeInfo', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_EmployeeInfo', to='masters.district')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division_EmployeeInfo', to='masters.division')),
                ('empType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empType_EmployeeInfo', to='setup.employeetype')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.gender')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_EmployeeInfo', to='masters.state')),
                ('tenantProfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenantProfile_EmployeeInfo', to='tenant.tenantprofile', verbose_name='Company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_EmployeeInfo', to=settings.AUTH_USER_MODEL)),
                ('empStatus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='empStatus_EmployeeInfo', to='employee.employeestatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
