# Generated by Django 6.0.5 on 2026-05-26 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_base_id_alter_profile_id'),
        ('employee', '0001_initial'),
        ('tenant', '0009_role_tenant_role_tenantp_0f7be2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_EmployeeInfo', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='userProfile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userProfile_EmployeeInfo', to='accounts.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_EmployeeInfo', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='mobile',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='tenantProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenantProfile_EmployeeInfo', to='tenant.tenantprofile', verbose_name='Tenant'),
        ),
    ]
