# Generated by Django 6.0.5 on 2026-05-26 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_base_id_alter_profile_id'),
        ('employee', '0002_employeeinfo_user_employeeinfo_userprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='is_profile_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_EmployeeInfo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='userProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userProfile_EmployeeInfo', to='accounts.profile'),
        ),
    ]
