# Generated by Django 6.0.5 on 2026-05-26 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeeinfo_is_profile_lock_alter_employeeinfo_user_and_more'),
        ('masters', '0010_district_masters_dis_zone_id_b0a27e_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCaste',
            fields=[
                ('employee_caste_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_caste_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('employee_caste_name',),
            },
        ),
        migrations.CreateModel(
            name='EmployeeRecruitmentCategory',
            fields=[
                ('recruitment_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('recruitment_category_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('recruitment_category_name',),
            },
        ),
        migrations.RenameField(
            model_name='employeeinfo',
            old_name='emergency_contact_name',
            new_name='religion',
        ),
        migrations.RemoveField(
            model_name='employeeinfo',
            name='country',
        ),
        migrations.RemoveField(
            model_name='employeeinfo',
            name='division',
        ),
        migrations.RemoveField(
            model_name='employeeinfo',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='employeeinfo',
            name='relationship',
        ),
        migrations.RemoveField(
            model_name='employeeinfo',
            name='state',
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='is_eligible_for_pf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='is_gratuity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='pf_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='hra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeAuditLog',
            fields=[
                ('remark', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_audit_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='Created by user', on_delete=django.db.models.deletion.CASCADE, related_name='created_by_EmployeeAuditLog', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeeinfo')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last updated by user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_EmployeeAuditLog', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='caste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caste_EmployeeInfo', to='employee.employeecaste'),
        ),
        migrations.CreateModel(
            name='EmployeeCertification',
            fields=[
                ('remark', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_certification_id', models.AutoField(primary_key=True, serialize=False)),
                ('certification_name', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_file', models.CharField(blank=True, max_length=500, null=True)),
                ('created_by', models.ForeignKey(help_text='Created by user', on_delete=django.db.models.deletion.CASCADE, related_name='created_by_EmployeeCertification', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='employee.employeeinfo')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last updated by user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_EmployeeCertification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('remark', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=500)),
                ('file_doc', models.CharField(blank=True, max_length=500, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(help_text='Created by user', on_delete=django.db.models.deletion.CASCADE, related_name='created_by_EmployeeDocument', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_documents', to='employee.employeeinfo')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last updated by user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_EmployeeDocument', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('remark', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_education_id', models.AutoField(primary_key=True, serialize=False)),
                ('qualification', models.CharField(max_length=500)),
                ('institution_name', models.CharField(max_length=200)),
                ('board_university', models.CharField(max_length=200)),
                ('passing_year', models.IntegerField()),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('certificate_file', models.CharField(blank=True, max_length=500, null=True)),
                ('created_by', models.ForeignKey(help_text='Created by user', on_delete=django.db.models.deletion.CASCADE, related_name='created_by_EmployeeEducation', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='employee.employeeinfo')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last updated by user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_EmployeeEducation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeExperience',
            fields=[
                ('remark', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=500)),
                ('department', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('last_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reason_for_leaving', models.TextField(blank=True)),
                ('reference_name', models.CharField(blank=True, max_length=250)),
                ('reference_contact', models.CharField(blank=True, max_length=20)),
                ('created_by', models.ForeignKey(help_text='Created by user', on_delete=django.db.models.deletion.CASCADE, related_name='created_by_EmployeeExperience', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='employee.employeeinfo')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last updated by user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_EmployeeExperience', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeFamilyDetail',
            fields=[
                ('employee_family_detail_id', models.AutoField(help_text='Unique family detail ID', primary_key=True, serialize=False)),
                ('family_member_name', models.CharField(help_text='Family member full name', max_length=150)),
                ('relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Spouse', 'Spouse'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Other', 'Other')], help_text='Relationship with employee', max_length=50)),
                ('date_of_birth', models.DateField(blank=True, help_text='Family member date of birth', null=True)),
                ('mobile_number', models.CharField(blank=True, help_text='Family member mobile number', max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, help_text='Family member occupation', max_length=100)),
                ('aadhaar_number', models.CharField(blank=True, help_text='Family member Aadhaar number', max_length=12, null=True)),
                ('is_emergency_contact', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(help_text='Created by user', on_delete=django.db.models.deletion.CASCADE, related_name='created_by_EmployeeFamilyDetail', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Related employee', on_delete=django.db.models.deletion.CASCADE, related_name='family_details', to='employee.employeeinfo')),
                ('gender', models.ForeignKey(blank=True, help_text='Family member gender', null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.gender')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last updated by user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_EmployeeFamilyDetail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Family Detail',
                'verbose_name_plural': 'Employee Family Details',
                'ordering': ('family_member_name',),
            },
        ),
        migrations.CreateModel(
            name='EmployeeJobHistory',
            fields=[
                ('remark', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_job_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(help_text='Created by user', on_delete=django.db.models.deletion.CASCADE, related_name='created_by_EmployeeJobHistory', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_history', to='employee.employeeinfo')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last updated by user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_EmployeeJobHistory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeLanguage',
            fields=[
                ('remark', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=100)),
                ('can_read', models.BooleanField(default=False)),
                ('can_write', models.BooleanField(default=False)),
                ('can_speak', models.BooleanField(default=False)),
                ('is_mother_tongue', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(help_text='Created by user', on_delete=django.db.models.deletion.CASCADE, related_name='created_by_EmployeeLanguage', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='employee.employeeinfo')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last updated by user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_EmployeeLanguage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeReportingManager',
            fields=[
                ('remark', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_reporting_manager_id', models.AutoField(help_text='Unique reporting manager record ID', primary_key=True, serialize=False)),
                ('is_current', models.BooleanField(default=True, help_text='Whether this is the current reporting manager')),
                ('created_by', models.ForeignKey(help_text='Created by user', on_delete=django.db.models.deletion.CASCADE, related_name='created_by_EmployeeReportingManager', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Employee assigned to reporting manager', on_delete=django.db.models.deletion.CASCADE, related_name='employee_reporting_managers', to='employee.employeeinfo')),
                ('reporting_manager', models.ForeignKey(help_text='Reporting manager employee', on_delete=django.db.models.deletion.CASCADE, related_name='manager_reporting_employees', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last updated by user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_EmployeeReportingManager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Reporting Manager',
                'verbose_name_plural': 'Employee Reporting Managers',
                'ordering': ('employee_reporting_manager_id',),
            },
        ),
    ]
