# Generated by Django 6.0.5 on 2026-05-26 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvalrules', '0001_initial'),
        ('employee', '0004_employeecaste_employeerecruitmentcategory_and_more'),
        ('tenant', '0009_role_tenant_role_tenantp_0f7be2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDataApprover',
            fields=[
                ('remark', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_data_approver_id', models.AutoField(primary_key=True, serialize=False)),
                ('approved_date', models.DateTimeField(blank=True, help_text='approved date', null=True)),
                ('rejected_date', models.DateTimeField(blank=True, help_text='rejected date', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('display_name', models.CharField(blank=True, help_text='Display name in table/form', max_length=100, null=True)),
                ('sequence', models.IntegerField(default=0)),
                ('approval_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_type_EmployeeDataApprover', to='approvalrules.approvaltype')),
                ('approver_by', models.ForeignKey(help_text='user-approver by', on_delete=django.db.models.deletion.CASCADE, related_name='user_EmployeeDataApprover', to=settings.AUTH_USER_MODEL)),
                ('approver_role', models.ForeignKey(blank=True, help_text='role of approver by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_EmployeeDataApprover', to='tenant.role')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_EmployeeDataApprover', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='employee', on_delete=django.db.models.deletion.CASCADE, related_name='employee_EmployeeDataApprover', to='employee.employeeinfo')),
                ('tenantProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenantProfile_EmployeeDataApprover', to='tenant.tenantprofile', verbose_name='Tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_EmployeeDataApprover', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sequence',),
            },
        ),
    ]
