# Generated by Django 6.0.5 on 2026-05-26 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvalrules', '0001_initial'),
        ('employee', '0005_employeedataapprover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedataapprover',
            old_name='approver_by',
            new_name='approver',
        ),
        migrations.RenameField(
            model_name='employeedataapprover',
            old_name='status',
            new_name='approverStatus',
        ),
        migrations.RemoveField(
            model_name='employeedataapprover',
            name='approval_type',
        ),
        migrations.RemoveField(
            model_name='employeedataapprover',
            name='display_name',
        ),
        migrations.AddField(
            model_name='employeedataapprover',
            name='approved_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedataapprover',
            name='approverType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='approverType_EmployeeDataApprover', to='approvalrules.approvaltype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeedataapprover',
            name='rejected_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeedataapprover',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeedataapprover',
            name='rejected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeActivityLog',
            fields=[
                ('remark', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_activity_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_EmployeeActivityLog', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_EmployeeActivityLog', to='employee.employeeinfo')),
            ],
            options={
                'ordering': ('employee_activity_log_id',),
            },
        ),
    ]
