# Generated by Django 6.0.5 on 2026-05-27 08:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_rename_approver_by_employeedataapprover_approver_and_more'),
        ('masters', '0010_district_masters_dis_zone_id_b0a27e_idx'),
        ('setup', '0009_remove_policestation_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempSelfRegEmployee',
            fields=[
                ('remark', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('temp_self_reg_employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('temp_self_reg_employee_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('employee_code', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('picture', models.CharField(blank=True, max_length=500, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=20)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('current_address', models.TextField(blank=True, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('employment_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Resigned', 'Resigned'), ('Terminated', 'Terminated')], default='Active', max_length=20)),
                ('work_location', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_address', models.CharField(blank=True, max_length=500)),
                ('bank_account_number', models.CharField(blank=True, max_length=30)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('is_gratuity', models.BooleanField(default=False)),
                ('is_eligible_for_pf', models.BooleanField(default=False)),
                ('pf_number', models.CharField(blank=True, max_length=20)),
                ('created_by_name', models.CharField(default='Self', max_length=50)),
                ('caste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caste_TempSelfRegEmployee', to='employee.employeecaste')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_TempSelfRegEmployee', to='masters.district')),
                ('empType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empType_TempSelfRegEmployee', to='setup.employeetype')),
                ('employeeInfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeeInfo_TempSelfRegEmployee', to='employee.employeeinfo')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.gender')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
