# Generated by Django 6.0.5 on 2026-05-28 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_tempselfregemployee'),
        ('setup', '0010_employeecategory'),
        ('tenant', '0009_role_tenant_role_tenantp_0f7be2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='empCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empCategory_EmployeeInfo', to='setup.employeecategory'),
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='empRole',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, related_name='empRole_EmployeeInfo', to='tenant.role'),
        ),
    ]
