# Generated by Django 6.0.5 on 2026-05-20 10:30

import django.db.models.deletion
import setup.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0009_role_tenant_role_tenantp_0f7be2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('remark', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('cost_center_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_center_name', models.CharField(max_length=1000)),
                ('cost_center_code', models.CharField(default=setup.models.generate_unique_code, max_length=8, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_CostCenter', to=settings.AUTH_USER_MODEL)),
                ('tenantProfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenantProfile_CostCenter', to='tenant.tenantprofile', verbose_name='Company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_CostCenter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('cost_center_name',),
            },
        ),
    ]
