# Generated by Django 6.0.5 on 2026-05-20 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
        ('tenant', '0009_role_tenant_role_tenantp_0f7be2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenterStatus',
            fields=[
                ('cost_center_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_center_status_name', models.CharField(max_length=500)),
                ('cost_center_status_css', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_cost_CostCenter', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='tenantProfile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_cost_CostCenter', to='tenant.tenantprofile', verbose_name='Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cost_CostCenter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CostCenterBulkUploadHistory',
            fields=[
                ('upload_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=1000)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('total_records', models.IntegerField(default=0)),
                ('processed_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('pending_records', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenantProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_cost_center_upload_history', to='tenant.tenantprofile')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_cost_center_files', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cost_center_upload_status', to='setup.costcenterstatus')),
            ],
            options={
                'ordering': ['-uploaded_on'],
            },
        ),
        migrations.AddField(
            model_name='costcenter',
            name='costCenterBulkUpload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costCenterBulkUpload_cost_centers', to='setup.costcenterbulkuploadhistory'),
        ),
    ]
