# Generated by Django 6.0.5 on 2026-05-25 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_shiftcategory_how_many_hours'),
        ('tenant', '0009_role_tenant_role_tenantp_0f7be2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('remark', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('holiday_id', models.AutoField(primary_key=True, serialize=False)),
                ('holiday_name', models.CharField(max_length=500)),
                ('holiday_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_national_holiday', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_Holiday', to=settings.AUTH_USER_MODEL)),
                ('tenantProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenantProfile_Holiday', to='tenant.tenantprofile', verbose_name='Tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_Holiday', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['holiday_date'],
            },
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('remark', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('police_station_id', models.AutoField(primary_key=True, serialize=False)),
                ('police_station_name', models.CharField(max_length=500)),
                ('station_code', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('picture_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_PoliceStation', to=settings.AUTH_USER_MODEL)),
                ('tenantProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenantProfile_PoliceStation', to='tenant.tenantprofile', verbose_name='Tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_PoliceStation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'police_station',
                'ordering': ['police_station_name'],
            },
        ),
    ]
