# Generated by Django 6.0.5 on 2026-05-25 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_city_zone'),
        ('setup', '0005_holiday_policestation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policestation',
            name='city',
        ),
        migrations.AddField(
            model_name='policestation',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='district_PoliceStation', to='masters.district', verbose_name='District'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policestation',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='division_PoliceStation', to='masters.division', verbose_name='Division'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policestation',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_PoliceStation', to='masters.zone', verbose_name='Zone'),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_PoliceStation', to='masters.state', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='policestation',
            name='City',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='City_PoliceStation', to='masters.city', verbose_name='City'),
        ),
    ]
