# Generated by Django 6.0.5 on 2026-05-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_remove_policestation_city_policestation_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policestation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
