# Generated by Django 6.0.5 on 2026-05-25 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_alter_policestation_address_and_more'),
        ('tenant', '0009_role_tenant_role_tenantp_0f7be2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftcategory',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftcategory',
            name='is_end_next_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shiftcategory',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeGroup',
            fields=[
                ('remark', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenantProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenantprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Group',
                'verbose_name_plural': 'Employee Groups',
                'ordering': ('name',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('tenantProfile', 'name'), name='setup_employee_group_tenant_name_uniq')],
            },
        ),
    ]
