# Generated by Django 6.0.5 on 2026-05-25 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_alter_zone_state'),
        ('setup', '0008_shiftcategory_end_time_shiftcategory_is_end_next_day_and_more'),
        ('tenant', '0009_role_tenant_role_tenantp_0f7be2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policestation',
            name='City',
        ),
        migrations.RemoveField(
            model_name='policestation',
            name='division',
        ),
        migrations.RemoveField(
            model_name='policestation',
            name='state',
        ),
        migrations.RemoveField(
            model_name='policestation',
            name='zone',
        ),
        migrations.CreateModel(
            name='HolidayDistrictWise',
            fields=[
                ('remark', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('holiday_district_wise_id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_HolidayDistrictWise', to='masters.district', verbose_name='District')),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_HolidayDistrictWise', to='setup.holiday', verbose_name='Holiday')),
                ('tenantProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenantProfile_HolidayDistrictWise', to='tenant.tenantprofile', verbose_name='Tenant')),
            ],
            options={
                'ordering': ['holiday_district_wise_id'],
            },
        ),
    ]
