# Generated by Django 6.0.5 on 2026-05-13 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_base'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Base',
        ),
    ]
