# Generated by Django 6.0.5 on 2026-05-16 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_base'),
        ('masters', '0004_district_masters_dis_state_i_025d22_idx_and_more'),
        ('tenant', '0008_role_role_desc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['tenantProfile'], name='accounts_pr_tenantP_08e0cc_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='accounts_pr_user_id_97e401_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['role'], name='accounts_pr_role_id_3cb92f_idx'),
        ),
        migrations.AddIndex(
            model_name='userlogintrace',
            index=models.Index(fields=['user', '-created_date'], name='accounts_us_user_id_c07dee_idx'),
        ),
    ]
