# Generated by Django 6.0.5 on 2026-05-20 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_accounts_pr_tenantp_08e0cc_idx_and_more'),
        ('masters', '0004_district_masters_dis_state_i_025d22_idx_and_more'),
        ('tenant', '0009_role_tenant_role_tenantp_0f7be2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.currency'),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_formate_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.dateformat'),
        ),
        migrations.AddField(
            model_name='profile',
            name='time_formate_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.timeformat'),
        ),
        migrations.AddField(
            model_name='profile',
            name='time_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.timezone'),
        ),
    ]
