# Generated by Django 6.0.5 on 2026-05-25 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0009_role_tenant_role_tenantp_0f7be2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalType',
            fields=[
                ('approval_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.IntegerField(default=0)),
                ('redirect_url', models.CharField(blank=True, help_text='Store redirect URL', max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('remark', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence', models.IntegerField(default=0)),
                ('sla_hrs', models.PositiveIntegerField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_approval_rules', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='tenant.role')),
                ('tenantProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='tenant.tenantprofile', verbose_name='Tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_approval_rules', to=settings.AUTH_USER_MODEL)),
                ('approval_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='approvalrules.approvaltype')),
            ],
            options={
                'ordering': ('sequence',),
            },
        ),
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('remark', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approver_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('display_name', models.CharField(blank=True, help_text='Display name in table/form', max_length=100, null=True)),
                ('sequence', models.IntegerField(default=0)),
                ('sla_hrs', models.PositiveIntegerField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(help_text='Related object ID')),
                ('approval_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='approvalrules.approvaltype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_approvers', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='tenant.role')),
                ('tenantProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='tenant.tenantprofile', verbose_name='Tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_approvers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sequence',),
            },
        ),
    ]
