"""
Django settings for DmtHrmsFmsApp project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = True
SECRET_KEY = os.getenv("SECRET_KEY")
ALLOWED_HOSTS = ['127.0.0.1', ]

# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'rest_framework.authtoken',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'masters',
    'tenant',
    'accounts',
    'setup',
    'user',
    'dashboard',
    'search'
]

# --- REST FRAMEWORK CONFIG ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ['rest_framework.authentication.TokenAuthentication', ],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated', ],
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend', ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 50,
}

# --- MIDDLEWARE ---
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middlewares.RoleMiddleware',
]

ROOT_URLCONF = 'DmtHrmsFmsApp.urls'

# --- TEMPLATES ---
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.menu_list',
            ],
            'libraries': {
                'ui_filter_tags': 'accounts.templatetags.ui_filter_tags',
            },
        },
    },
]

WSGI_APPLICATION = 'DmtHrmsFmsApp.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DATABASE_NAME', 'PROCURE_10_X_DB'),
        'USER': os.getenv('USER_NAME', 'PROCURE_10_X_DB'),
        'PASSWORD': os.getenv('PASSWORD', 'PROCURE10X@2026'),
        'HOST': os.getenv('HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'CONN_MAX_AGE': 300,
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# STATIC_ROOT = 'static'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static"), ]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

DATABASE_NAME = os.getenv('DATABASE_NAME')
USER_NAME = os.getenv('USER_NAME')
PASSWORD = os.getenv('PASSWORD')
HOST = os.getenv('HOST')
PORT = os.getenv('DB_PORT')

IS_RunServer = os.getenv('IS_RunServer') == 'True'
AUTO_LOGOUT = os.getenv('AUTO_LOGOUT') == 'True'

# SMS Notification
SMS_API = os.getenv('SMS_API')
DIGIMIND_OTP = os.getenv('DIGIMIND_OTP')
SMS_SERVICE_ON = os.getenv('SMS_SERVICE_ON') == 'True'

# Email Configuration
EMAIL_SERVICE_ON = os.getenv('EMAIL_SERVICE_ON', 'True') == 'True'
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

EMAIL_BCC = os.getenv('EMAIL_BCC', '')
EMAIL_CC = os.getenv('EMAIL_CC', '')
EMAIL_FROM_ADDRESS = os.getenv('EMAIL_FROM_ADDRESS', '')
EMAIL_FROM_ADDRESS_NAME = os.getenv('EMAIL_FROM_ADDRESS_NAME', '')
EMAIL_OTP_SUBJECT = os.getenv('EMAIL_OTP_SUBJECT', '')
EMAIL_VERIFICATION_SUBJECT = os.getenv('EMAIL_VERIFICATION_SUBJECT', '')
EMAIL_VERIFICATION_URL = os.getenv('EMAIL_VERIFICATION_URL', '')
EMAIL_LOGIN_URL = os.getenv('EMAIL_LOGIN_URL', '')

# --- AWS / S3 CONFIG ---
S3_BUCKET_NAME = os.getenv('S3_BUCKET_NAME')
S3_FOLDER = os.getenv('S3_FOLDER')
S3_URL = os.getenv('S3_URL')
aws_access_key_id = os.getenv('AWS_ACCESS_KEY_ID')
aws_secret_access_key = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', os.getenv('AWS_DEFAULT_REGION', 'ap-south-1'))
AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL')
FILE_UPLOAD_STORAGE = os.getenv('FILE_UPLOAD_STORAGE', 's3')
IS_FILE_UPLOAD_S3 = os.getenv('IS_FILE_UPLOAD_S3', 'True') == 'True'

# --- CUSTOM VARIABLES ---
DEFAULT_PAGE_SIZE = os.getenv("DEFAULT_PAGE_SIZE")
ENCRYPT_KEY = os.getenv("ENCRYPT_KEY")
COPY_RIGHT_INFORMATION = os.getenv('COPY_RIGHT_INFORMATION')
API_URL = os.getenv('API_URL')

LOGIN_URL = os.getenv('LOGIN_REDIRECT_URL')
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS')
