# Generated by Django 6.0.5 on 2026-05-28 11:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0010_district_masters_dis_zone_id_b0a27e_idx'),
        ('tenant', '0009_role_tenant_role_tenantp_0f7be2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerType',
            fields=[
                ('trainer_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('trainer_type_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('trainer_type_name',),
            },
        ),
        migrations.CreateModel(
            name='TrainingStatus',
            fields=[
                ('training_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('training_status_name', models.CharField(max_length=100, unique=True)),
                ('training_status_css', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('training_status_id',),
            },
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('training_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('training_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('training_name',),
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('remark', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trainer_id', models.AutoField(primary_key=True, serialize=False)),
                ('trainer_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('trainer_or_organization_name', models.CharField(max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=20)),
                ('specialization', models.TextField(blank=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.CharField(blank=True, max_length=500, null=True)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('address', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_trainer', to=settings.AUTH_USER_MODEL)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.gender')),
                ('tenantProfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenantProfile_trainer', to='tenant.tenantprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_trainer', to=settings.AUTH_USER_MODEL)),
                ('trainerType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='training.trainertype')),
            ],
            options={
                'ordering': ['trainer_or_organization_name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('remark', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('training_program_id', models.AutoField(primary_key=True, serialize=False)),
                ('training_program_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('training_title', models.CharField(max_length=500)),
                ('training_program_picture', models.CharField(blank=True, max_length=500, null=True)),
                ('batch_size', models.PositiveIntegerField(default=0)),
                ('training_content', models.TextField()),
                ('venue', models.CharField(max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_payable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('training_program_doc', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_training_programs', to=settings.AUTH_USER_MODEL)),
                ('tenantProfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_programs', to='tenant.tenantprofile')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_training_programs', to='training.trainer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_training_programs', to=settings.AUTH_USER_MODEL)),
                ('trainingStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainingStatus_training_programs', to='training.trainingstatus')),
                ('trainingType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainingType_training_programs', to='training.trainingtype')),
            ],
            options={
                'ordering': ['training_title'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgramAttendee',
            fields=[
                ('remark', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('training_program_attendee_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_days', models.IntegerField(default=0)),
                ('no_of_day_attendant', models.IntegerField(default=0)),
                ('no_of_day_not_attendant', models.IntegerField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('remark_feedback', models.TextField(blank=True)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('trainingProgram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='training.trainingprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['training_program_attendee_id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingWiseTrainer',
            fields=[
                ('training_wise_trainer_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_TrainingWiseTrainer', to='training.trainer')),
                ('trainingType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainingType_TrainingWiseTrainer', to='training.trainingtype')),
            ],
            options={
                'ordering': ('training_wise_trainer_id',),
            },
        ),
    ]
