# Generated by Django 6.0.5 on 2026-05-28 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0010_employeecategory'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='trainerType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='setup.trainertype'),
        ),
        migrations.DeleteModel(
            name='TrainerType',
        ),
    ]
